### PR TITLE
Combined keywords into a single email

### PR DESCRIPTION
**Pull request by tfnribeiro**
Combined the keywords into a single email body:

image

Should avoid spamming users emails if they have multiple searches.

### CODE REVIEW

**Comment by mircealungu** [comment]
Should we also add a link to where the searches can be found? i.e. `https://www.zeeguu.org/articles/mySearches`?

**Comment by mircealungu** [comment]
I see an A/B testing opportunity here: one approach just mentions that there are new articles. The other one provides titles and links too :)

**Comment by tfnribeiro** [comment]
That's also a good idea! 

Added the link;

image

**Review by mircealungu — APPROVED** [review]
thanks @tfnribeiro . I've added one extra line-break before the "Cheers". We should also consider replacing `"Cheers"` with `cheers(flask.g.user.learned_language)` at some point in the future :) 

But for now it's good... Let's wait for @KlaraK94's review and then we can deploy.

**Comment by KlaraK94** [comment]
Looks good! Nice, that the user will not get spammed, and I think the issue with my version - was that it was not using subscription.search.keywords :-)

**Review by mircealungu — APPROVED** [review]
ok. merging then.

**Pull request merged**
